version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    container_name: practice_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - practice_postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: practice_pgweb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8081"
    depends_on:
      db:
        condition: service_healthy

volumes:
  practice_postgres_data: